### ISSUE TITLE
new script (localization)

### ISSUE THREAD

**Issue by darynakarmazin** [savchenkolex/powerkit-ua-site#140]

**Comment by savchenkolex** [comment]
Я дивився код, але не перевіряв в роботі і не можу сказати, що все зрозумів. Зробив окремі домени, щоб задеплоїти, але зроблю це після перерви.

**Comment by darynakarmazin** [comment]
Гілка з локалізацією задеплоїна тут:
https://pklang.awake-tools.online

**Comment by darynakarmazin** [comment]
Це посилання, відповідно, показує статус деплоя гілки з локалізацією : 
https://pklang.awake-tools.online/gitpull.php?gitpull=BVcV3A1ZkmVbvr9uupiCv

(спроба оновлення з гітхабу кожні 15 хвилин)

**Comment by NastyaLatysh** [comment]
1. https://take.ms/Xlj6p0 - в англ версії треба прибрати точку в кінці тексту біля панера 
2. https://take.ms/3b0uu - Так як ми робили апдет тексту в укр версії, то треба зробитит і в анг версії. У блоці «faq» у 2 пункті треба змінити відповідь на 
3. https://take.ms/THaZD - В англ версіі в блоці «скільки зроблено паверів» текст не співпадає з докою 
4. https://take.ms/ny8AG - в англ версії в кукі поп-апі кнопка "закрити" налазить на кнопку "згоден" (mobile)

**Comment by darynakarmazin** [comment]
i. Hero-title оновила:

![Image](https://github.com/savchenkolex/powerkit-ua-site/assets/110288504/14c4bd76-c8d6-498d-8dd6-e0d602ba9008)

**Comment by darynakarmazin** [comment]
ii. Оновлено текст faq-answer2: 

![Image](https://github.com/savchenkolex/powerkit-ua-site/assets/110288504/3406cde8-09c2-4482-b489-0e4ebcb6cec4)

**Comment by darynakarmazin** [comment]
iii.  Оновлено текст amount-discription-pw (en)

![Image](https://github.com/savchenkolex/powerkit-ua-site/assets/110288504/43bc389e-eebe-4d80-98f7-85f0de5bf2a7)

**Comment by darynakarmazin** [comment]
iv. Оновлено розміщення modal-content-btn (мобільний англ версія):


![Image](https://github.com/savchenkolex/powerkit-ua-site/assets/110288504/012bd8c8-61c9-4466-ac2a-60de0d02d266)
