### ISSUE TITLE
bug hover on logo after open link on mobile

### ISSUE THREAD

**Issue by savchenkolex** [savchenkolex/powerkit-ua-site#153]
1. https://take.ms/Bq1Ed - в мобайлі при кліку на лого перекидає на відповідне посилання, але після повернення на наш лендінг - збільшене лого та підствітка залишається. Чи можна це пофіксити?

**Comment by savchenkolex** [comment]
Спробував зробити через відміну властивостей ховера при події фокус і актів. Оскільки на мобільному через відсутність курсору мишки подія тач інтерпретується бо зна як в комбінації цих подій.

**Comment by NastyaLatysh** [comment]
https://take.ms/Vp2HOo - відтворюється на iphone

**Comment by darynakarmazin** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/hover

https://habr.com/ru/companies/ruvds/articles/556156/

**Comment by NastyaLatysh** [comment]
на айфонах ок - при натасненні на лого воно підсвічується, але потім швидень повертається в початкове положення 
але на андроїдаї немає такої підсвітки, чи будь якого виділення/фокусу https://take.ms/j92gW

**Comment by darynakarmazin** [comment]
Додано медіа правило для самсунгів.

**Comment by NastyaLatysh** [comment]
в мене відтворюється проблема

**Comment by NastyaLatysh** [comment]
а ми можем просто фокус додати для таких смартфонів, щоб не заморочуватись з підсвіткою ?
