### ISSUE TITLE
set telegram logo as svg icon

### ISSUE THREAD

**Issue by savchenkolex** [savchenkolex/powerkit-ua-site#216]
![Image](https://github.com/savchenkolex/powerkit-ua-site/assets/42295550/268324c0-4ac8-41f0-8400-780976bd2390)

**Comment by savchenkolex** [comment]
виходить, що іконки соцмереж на сайті зроблені по різному.

**Comment by NastyaLatysh** [comment]
візуально для юзера ті лого ніяк не відрізняються, тому не бачу сенсу це змінювати
