### ISSUE TITLE
problem loading pictures

### ISSUE THREAD

**Issue by NastyaLatysh** [savchenkolex/powerkit-ua-site#219]
Досі зустрічається проблема із завантаженням картинок 

Теорія одного з волонтерів:
Можливо вони не підвантажуються через обмеження хостинга на загрузку .webp зображень, тож картинка завантажується довго і сервер обрубує зʼєднання.
Можливо проблема вирішиться зміною налаштувань хостинга

**Comment by savchenkolex** [comment]
` <picture>
            <source
              media="(min-width: 1440px)"
              srcset="
                ../images/section-review/d-review-0.webp    1x,
                ../images/section-review/d-review-0@2x.webp 2x
              "
              type="image/webp"
            >
            <source
              media="(min-width: 1440px)"
              srcset="
                ../images/section-review/d-review-0.jpg    1x,
                ../images/section-review/d-review-0@2x.jpg 2x
              "
              type="image/jpeg"
            >
            <source
              media="(min-width: 768px)"
              srcset="
                ../images/section-review/t-review-0.webp    1x,
                ../images/section-review/t-review-0@2x.webp 2x
              "
              type="image/webp"
            >
            <source
              media="(min-width: 768px)"
              srcset="
                ../images/section-review/t-review-0.jpg    1x,
                ../images/section-review/t-review-0@2x.jpg 2x
              "
              type="image/jpeg"
            >
            <source
              media="(min-width: 320px)"
              srcset="
                ../images/section-review/m-review-0.webp    1x,
                ../images/section-review/m-review-0@2x.webp 2x
              "
              type="image/webp"
            >
            <source
              media="(min-width: 320px)"
              srcset="
                ../images/section-review/m-review-0.jpg    1x,
                ../images/section-review/m-review-0@2x.jpg 2x
              "
              type="image/jpeg"
            >
            <img
              src="../images/section-review/d-review-0.jpg"
              alt=""
            >
          </picture>`

**Comment by savchenkolex** [comment]
В нас прописано таким синтаксисом, що в браузера є вибір розміру і типу файлу зображення і якщо нічого не підійшло, використати посилання з простого тегу img

**Comment by savchenkolex** [comment]
Потрібно знайти, як відтворити цей баг і зрозуміти, що не підтримується насправді.

**Comment by savchenkolex** [comment]
```
macos: Ventura Version 13.1 (22C65)
Chrome: Version 114.0.5735.198 (Official Build) (arm64)
```

**Comment by NastyaLatysh** [comment]
Вирішили скіпнути, так як не можем відтворити цей баг
