### ISSUE TITLE
fix content

### ISSUE THREAD

**Issue by NastyaLatysh** [savchenkolex/powerkit-ua-site#234]
1. Повторюється текст в укр версії - https://tppr.me/j2myk
2. Змінити в контенті слово "проект" на “проєкт”
3. В контенті додати кому: перед “щоб” , “Так само, як і його”
4. Кнопку "донат" змінити на “Задонатити”
5. Є невеличкі правки по англ версії, дивитись у закріплений файл 
[powerkit.docx](https://github.com/savchenkolex/powerkit-ua-site/files/12067014/powerkit.docx)

**Comment by darynakarmazin** [comment]
1. 

![Image](https://github.com/savchenkolex/powerkit-ua-site/assets/110288504/6cd3f70c-8c81-441f-a6ff-6f55eeee5c03)

**Comment by darynakarmazin** [comment]
2. 

![Image](https://github.com/savchenkolex/powerkit-ua-site/assets/110288504/7c0ffc23-e154-454a-bb98-7f1e351ba256)

**Comment by darynakarmazin** [comment]
4. чекаю відповідь

**Comment by darynakarmazin** [comment]
5. 

![Image](https://github.com/savchenkolex/powerkit-ua-site/assets/110288504/08e83702-3488-4a1d-af82-1c8b26c91810)

**Comment by NastyaLatysh** [comment]
1. https://take.ms/Py1wQ, https://take.ms/eirzg , https://take.ms/k4zn7 - треба трішки виправити текст на англ мові відповідно до закріпленого файлу в задачі

**Comment by darynakarmazin** [comment]
Зміни внесені в таблиці перекладу. Pull requests 'content fix'


![Image](https://github.com/savchenkolex/powerkit-ua-site/assets/110288504/a43d5c1b-2d7f-4e1a-b1e8-978dab4f2372)

**Comment by darynakarmazin** [comment]
![Image](https://github.com/savchenkolex/powerkit-ua-site/assets/110288504/e929b88e-0c28-4ae2-9952-401345e43100)

**Comment by darynakarmazin** [comment]
![Image](https://github.com/savchenkolex/powerkit-ua-site/assets/110288504/70a29832-35d6-4dd1-8c40-ea332af4469d)

**Comment by darynakarmazin** [comment]
![Image](https://github.com/savchenkolex/powerkit-ua-site/assets/110288504/ed71b937-bc6c-4902-ad55-01fdb2e22390)

**Comment by NastyaLatysh** [comment]
https://take.ms/sgnf6 - відтворюється ,треба трішки змінити анг контент

**Comment by savchenkolex** [comment]
нічого робити не треба

![Image](https://github.com/savchenkolex/powerkit-ua-site/assets/42295550/95c20d94-d15a-4dfb-a628-23e81a75cbaa)
