### ISSUE TITLE
increasing the image size in the gallery

### ISSUE THREAD

**Issue by savchenkolex** [savchenkolex/powerkit-ua-site#240]

**Comment by NastyaLatysh** [comment]
1. https://take.ms/bVjKd - при закритті фотографії вона збільшується і закривається майжк на весь екран. 
2. https://take.ms/51W8V - треба додати відповідний курсор на клікабельні елементи (фотографії), щоб юзер розумів що на них можна натиснути (десктоп)

**Comment by savchenkolex** [comment]
- fix duble-scale animation 
- add cursor pointer on pictures
- set body no scroll when backdrop open
- add js exception for legal page (if haven`t pictures and backdrop - do nothing )
- adjust increasing image and cross position
